# build:  docker-compose build --no-cache 
version: "3"


services:
  flare:
    build:
      context: ../images/flare_observation
      dockerfile: Dockerfile
    environment:
      PUBLIC_IP: "${BIND_ADDRESS}"
    ports:
      - ${BIND_ADDRESS}:9650:9650
      - ${BIND_ADDRESS}:9651:9651
    volumes:
      - ${LOCAL_DATA_DIR}:/data/flare-data
      - ${LOCAL_LOGS_DIR}:/data/flare-logs
      - ${LOCAL_CONF_DIR}:/data/flare-conf
    networks:
      flarenet:
         ipv4_address: 172.19.0.10
networks:
    flarenet:
      ipam:
        driver: default
        config:
          - subnet: 172.19.0.0/24
